'use strict';

const CANONICAL_DIMENSIONS = Object.freeze({
  LIVENESS: 'liveness',
  SESSION_LIFECYCLE: 'sessionLifecycle',
  TURN: 'turnState',
  ACTIVITY: 'activityState',
  ATTENTION: 'attentionState',
});

const LIVENESS_STATES = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  ALIVE: 'ALIVE',
  SUSPECT: 'SUSPECT',
  DEAD: 'DEAD',
});

const SESSION_LIFECYCLE_STATES = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  OPEN: 'OPEN',
  CLOSING: 'CLOSING',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
  LOST: 'LOST',
});

const TURN_STATES = Object.freeze({
  NONE: 'NONE',
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  COMPLETION_CANDIDATE: 'COMPLETION_CANDIDATE',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  INTERRUPTED: 'INTERRUPTED',
});

const ACTIVITY_STATES = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  IDLE: 'IDLE',
  PLANNING: 'PLANNING',
  THINKING: 'THINKING',
  USING_TOOL: 'USING_TOOL',
  RUNNING_COMMAND: 'RUNNING_COMMAND',
  RUNNING_SUBAGENT: 'RUNNING_SUBAGENT',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  WAITING_USER: 'WAITING_USER',
  WAITING_EXTERNAL: 'WAITING_EXTERNAL',
  COMPACTING_CONTEXT: 'COMPACTING_CONTEXT',
  RATE_LIMITED: 'RATE_LIMITED',
});

const ATTENTION_STATES = Object.freeze({
  NONE: 'NONE',
  ACTION_REQUIRED: 'ACTION_REQUIRED',
  COMPLETED_UNSEEN: 'COMPLETED_UNSEEN',
  FAILED_UNSEEN: 'FAILED_UNSEEN',
  INTERRUPTED_UNSEEN: 'INTERRUPTED_UNSEEN',
  RATE_LIMITED: 'RATE_LIMITED',
});

const EVIDENCE_SOURCES = Object.freeze({
  NATIVE_HOOK: 'native_hook',
  JSONL: 'jsonl',
  DATABASE: 'database',
  PROCESS: 'process',
  HEARTBEAT: 'heartbeat',
  APP_SERVER: 'app_server',
  TERMINAL: 'terminal',
  PTY: 'pty',
  UI: 'ui',
  MANUAL: 'manual',
  LEGACY_FALLBACK: 'legacy_fallback',
});

const SOURCE_HEALTH_STATES = Object.freeze({
  HEALTHY: 'HEALTHY',
  DEGRADED: 'DEGRADED',
  DISCONNECTED: 'DISCONNECTED',
  UNSUPPORTED: 'UNSUPPORTED',
});

const EVENT_TYPES = Object.freeze({
  SESSION_DISCOVERED: 'SESSION_DISCOVERED',
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_CLOSING: 'SESSION_CLOSING',
  SESSION_CLOSED: 'SESSION_CLOSED',
  SESSION_ARCHIVED: 'SESSION_ARCHIVED',
  TURN_STARTED: 'TURN_STARTED',
  TURN_COMPLETION_SIGNAL: 'TURN_COMPLETION_SIGNAL',
  TURN_COMPLETED: 'TURN_COMPLETED',
  TURN_FAILED: 'TURN_FAILED',
  TURN_INTERRUPTED: 'TURN_INTERRUPTED',
  USER_MESSAGE: 'USER_MESSAGE',
  ASSISTANT_MESSAGE: 'ASSISTANT_MESSAGE',
  TOOL_STARTED: 'TOOL_STARTED',
  TOOL_FINISHED: 'TOOL_FINISHED',
  SUBAGENT_STARTED: 'SUBAGENT_STARTED',
  SUBAGENT_FINISHED: 'SUBAGENT_FINISHED',
  WAITING_APPROVAL: 'WAITING_APPROVAL',
  WAITING_USER: 'WAITING_USER',
  WAITING_EXTERNAL: 'WAITING_EXTERNAL',
  PROCESS_SEEN: 'PROCESS_SEEN',
  PROCESS_MISSING: 'PROCESS_MISSING',
  PROCESS_DEAD: 'PROCESS_DEAD',
  HEARTBEAT: 'HEARTBEAT',
  TRANSCRIPT_ACTIVITY: 'TRANSCRIPT_ACTIVITY',
  RATE_LIMITED: 'RATE_LIMITED',
  CONTEXT_COMPACTING: 'CONTEXT_COMPACTING',
  MANUAL_OVERRIDE: 'MANUAL_OVERRIDE',
});

module.exports = {
  CANONICAL_DIMENSIONS,
  LIVENESS_STATES,
  SESSION_LIFECYCLE_STATES,
  TURN_STATES,
  ACTIVITY_STATES,
  ATTENTION_STATES,
  EVIDENCE_SOURCES,
  SOURCE_HEALTH_STATES,
  EVENT_TYPES,
};
